# embed_file(<file> <symbol> <header>)
#
# Writes <header> declaring `inline const unsigned char <symbol>[]` with the
# bytes of <file>, and `<symbol>_size`: a picture or a catalogue compiled into
# the program, so it cannot go missing from beside it. Configure depends on
# the file, so changing it regenerates the header.
function(embed_file file symbol header)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${file}")
    file(READ "${file}" hex HEX)
    string(LENGTH "${hex}" length)
    math(EXPR size "${length} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    # Sixteen to a line, so the header stays readable in a diff tool.
    string(REGEX REPLACE "((0x..,){16})" "\\1\n    " bytes "${bytes}")
    file(WRITE "${header}"
        "// Generated by cmake/embed_file.cmake from ${file}. Do not edit.\n"
        "#pragma once\n"
        "#include <cstddef>\n"
        "inline const unsigned char ${symbol}[] = {\n    ${bytes}\n};\n"
        "inline constexpr std::size_t ${symbol}_size = ${size};\n")
endfunction()
